# Generated by Django 5.0.4 on 2024-04-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('Complaint', 'Complaint Request'), ('Service', 'Service Request'), ('Booking', 'Booking Request'), ('Other', 'Other Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest1',
            name='priority',
            field=models.CharField(choices=[('1', '1️⃣'), ('2', '2️⃣'), ('3', '3️⃣'), ('4', '4️⃣'), ('5', '5️⃣'), ('6', '6️⃣'), ('7', '7️⃣'), ('8', '8️⃣'), ('9', '9️⃣'), ('10', '🔟')], max_length=2, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='servicerequest1',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], max_length=10, verbose_name='Status'),
        ),
    ]
