# Generated by Django 5.0.4 on 2024-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicerequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('R', 'Received'), ('I', 'In Review'), ('C', 'Completed'), ('P', 'Pending')], default='P', max_length=20),
        ),
        migrations.DeleteModel(
            name='ServiceRequest1',
        ),
    ]
