# Generated by Django 5.0.4 on 2024-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicerequest_status_delete_servicerequest1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('R', 'Received'), ('I', 'In Review'), ('C', 'Completed'), ('P', 'Pending')], default='S', max_length=20),
        ),
    ]
